version: '3'

services:

  djangodev:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - "6043:8000"
    depends_on:
      - dbdjango
    # environment:
      # DJANGO_SECRET_KEY: 1234
      # SECRET_KEY: 1234
      # MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
    networks:
      - one      

  dbdjango:
    image: mysql:5.7.22
    restart: always
    # container_name: mysqlpython
    env_file:
      - .env
    # environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
      # MYSQL_USER: dev
      # MYSQL_PASSWORD: dev
    ports:
      - "6044:3306"
    volumes:
      - ../data/mysql382dev/:/var/lib/mysql/
    networks:
      - one      
      

      
networks:
  one:      