version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - "6033:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: 1234
      SECRET_KEY: 1234
      # MYSQL_ROOT_PASSWORD: root

